### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by MawsayB** [dehotz/liftoff-assignments#5]
1) remove "https://" on the GitHub url
2) update "1 million dollars" to "$1M"
3) Capitalize "**S**umma **C**um **L**aude"

**Comment by dehotz** [comment]
Adjusted all but the latin honors, they're supposed to stay lowercase, I got yelled at about that before :)

I do wonder if I should include LC101 in the resume though, and frankly I still think I can find a better style for it, so I may change that later.

(http://grammarist.com/spelling/summa-cum-laude-or-magna-cum-laude/)
